#!/usr/bin/env bash

cd $(dirname $0)/..

trap "docker-compose down" 0

docker-compose run --service-ports --rm dev bash -x -c "pip install -r requirements.txt && pip install -r dev-requirements.txt && ${@-sh}"
